// Draft TP2 modules and per-device handles are separate from backbone experts.
#define CUTEAFD_V41_DSPARK_TP2_EXPERTS 1
#define CUTEAFD_V41_LOCAL_EXPERTS 1
#define CUTEAFD_V41_TP2_EXPERTS 1
#define cuteafd_expert_info cuteafd_v41_dspark_tp2_expert_info
#define cuteafd_expert_initialize cuteafd_v41_dspark_tp2_expert_initialize
#define cuteafd_expert_output_kind cuteafd_v41_dspark_tp2_expert_output_kind
#define cuteafd_expert_bind_scratch cuteafd_v41_dspark_tp2_expert_bind_scratch
#define cuteafd_expert_initialize_scratch_async cuteafd_v41_dspark_tp2_expert_initialize_scratch_async
#define cuteafd_expert_launch cuteafd_v41_dspark_tp2_expert_launch
#include "v41_experts.cc"
