// Separate immutable variant table and handles; share the validated launch ABI.
#define CUTEAFD_V41_LOCAL_EXPERTS 1
#define cuteafd_v41_expert_info cuteafd_v41_local_expert_info
#define cuteafd_v41_expert_initialize cuteafd_v41_local_expert_initialize
#define cuteafd_v41_expert_output_kind cuteafd_v41_local_expert_output_kind
#define cuteafd_v41_expert_bind_scratch cuteafd_v41_local_expert_bind_scratch
#define cuteafd_v41_expert_initialize_scratch_async cuteafd_v41_local_expert_initialize_scratch_async
#define cuteafd_v41_expert_launch cuteafd_v41_local_expert_launch
#include "v41_experts.cc"
